### ISSUE TITLE
Hardcoded file names

### ISSUE THREAD

**Issue by pyamsoft** [peterhn/cs121-crawler#1]
In a couple of the files, there are multiple instances of hardcoded path strings for a specific machine.

Please create a public variable in the main class which will contain the path string. This will make it easier for others to adopt the code as we won't have to dig around the project looking for each instance of the hardcoded path on our specific machines.

Can submit a pull request if you want, but its not the largest problem at the moment.

**Comment by peterhn** [comment]
Yeah sure sounds good. Would you also be able to meet tomorrow?

Peter

**Comment by pyamsoft** [comment]
I am available after 3pm
