### ISSUE TITLE
ICS Domain

### ISSUE THREAD

**Issue by pyamsoft** [peterhn/cs121-crawler#8]
So I'm timed out from the ICS domain I guess for crawling too much

While it is temporary, it is a period of time where no work will get done.

If anybody would like to take over, feel free to. There is not much more coding to be done with the crawling part.

The master branch is up to date, so if you pull it and build the crawler, you can run it.

If not, I should be getting back to the ICS domain on the weekend, so I will start again then if nobody else has at that time.

**Comment by peterhn** [comment]
What's your update on the crawling? Do you have to start over?

**Comment by pyamsoft** [comment]
The crawler has finished and I have uploaded the contents as a GDrive document.
